### PR TITLE
View all saved movie rating annabella

### PR DESCRIPTION
**Pull request by AnnabellAnastasia**

### CODE REVIEW

**Comment by ukiah-sperry** [comment]
LGTM 🔥

**Review by ukiah-sperry — APPROVED** [review]
HOORAY

**Review by KaptainNexus — APPROVED** [review]
LGTM

**Review by Sam-Is-Red — APPROVED** [review]
Looks good :D

**Comment by AnnabellAnastasia** [comment]
lgtm

**Review by AnnabellAnastasia — COMMENTED** [review]
lgtm

**Pull request merged**
